### ISSUE TITLE
JavaScript group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by alef-garrido** [alef-garrido/API-based-capstone#21]
Only two members in the team. Myself (alef-garrido) and David (petumazo).

Link: https://github.com/alef-garrido/API-based-capstone

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @alef-garrido  &  @petumazo, 

Good job on implementing all the requirements. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
